baseURL = "https://jonathanyeong.com/"
languageCode = "en-us"
theme = "tale-theme"
title = "Jonathan Yeong"
pygmentsUseClassic = true
pygmentsCodeFences = true
[taxonomies]
   tag = "tags"
[staticman]
  endpoint = "https://personal-site-comments.herokuapp.com/v2/entry/"
  username = "jonathanyeong"
  repository = "personal-site"
  branch = "master"