[[edge_functions]]
  function = "og"
  path = "/og-image"
[build.environment]
  TZ="America/Toronto"
[[redirects]]
  from = "/garden/how-to-setup-ci-with-phoenix-github-actions/"
  to = "/writing/how-to-setup-ci-with-phoenix-github-actions"
  status = 301
