name: "Fetch Content Updates"
on: [repository_dispatch, workflow_dispatch]
jobs:
  pull_content_updates:
    name: pull_content_updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Pull submodule
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive --remote
      - name: Push changes
        run: |        
          git add .
          git commit -m "Updating content"
          git push
    
